const arrayCriaturasPlayer2 = [
    {
        id: 0,
        status: [],
        nome: "Acid Blob",
        img: "./src/img/criaturas/Acid_Blob.gif",
        hpTotal: 250,
        hp: 250,
        xp: 250,
        stamina: 30,
        velocidade: 60,
        estrela: 3,
        raridade: 1,
        charm: 25,
        ataqueFisico: 77,
        defesa: 3,
        ataqueMagico: [{earth: 88, holy: 0, ice: 0, fire: 0, physical: 0, death: 0, energy: 0, drain: 0}],
        resistencia: [{earth: 100, holy: 0, ice: 20, fire: -10, physical: 0, death: 100, energy: -10, drain: 0}],
        habilidades: [{heal: 0, veneno: 0, drunk: 0, haste: 0, paralyze: 0, imuneParalyze: 0, summon: "Acid Blob", debuff: 25, invisivel: 0, verInvisivel: 0}],
        sons: ["Kzzchhhh"],
        loot: ["Glob of Acid Slime"],
        desc: "Altamente destrutivo e corrosivo. Bolhas ácidas têm pouco em comum com lodo comum. Eles são muito melhores em encontrar e alcançar seu objetivo do que seus primos distantes. Enquanto a lama comum é impulsionada pelo desejo original de obter comida, a Gota de Ácido está agora voltada para a destruição. É realmente uma visão aterrorizante quando um grupo dessas criaturas rasteja em direção a um único alvo com a intenção de destruí-lo completamente. Alguns pesquisadores especulam que bolhas de ácido compartilham sua inteligência com pontos ao redor do mundo. Como uma Gota de Ácido é recriada dividindo-se em duas unidades, mas esta tese pode ter um grão de verdade nele. Uma vez que os seres vivos são muitas vezes inteligentes e rápidos o suficiente para escapar dos ataques do Spot, qualquer tipo de planta, os edifícios geralmente não são tão felizes e são aniquilados por seus ataques. No passado, alguns lunáticos excêntricos usavam Acid Blobs para descartar resíduos que eram considerados um pouco elegantes. No entanto, depois de digerir uma certa quantidade de resíduos, a Gota de Ácido começou a se reproduzir repetidamente, e então o problema real começou. Depois de vários incidentes desagradáveis, esta forma de descarte de resíduos foi interrompida, no entanto, os resultados de tal loucura ainda são visíveis em vários lugares.",
        local: ["Deep Banuta", "Yalahar Alchemist Quarter"],
    },
    {
        id: 1,
        status: [],
        nome: "Acolyte of the Cult",
        img: "./src/img/criaturas/acolyte_of_the_cult.gif",
        hpTotal: 390,
        hp: 390,
        xp: 300,
        stamina: 30,
        velocidade: 100,
        estrela: 3,
        raridade: 1,
        charm: 25,
        ataqueFisico: 65,
        defesa: 30,
        ataqueMagico: [{earth: 0, holy: 0, ice: 0, fire: 0, physical: 0, death: 0, energy: 0, drain: 215}],
        resistencia: [{earth: +20, holy: +20, ice: +20, fire: 0, physical: -10, death: -5, energy: -10, drain: 0}],
        habilidades: [{heal: 50, veneno: 2, drunk: 1.3, haste: 25, paralyze: 0, imuneParalyze: 0, summon: "Skeleton", debuff: 0, invisivel: true, verInvisivel: true}],
        sons: ["Praise Voodoo!", "Power to the cult!", "Feel the power of the cult!"],
        loot: ["Platinum Coin", "Cultish Robe", "Rope Belt", "Morning Star", "Orange Book", "Small Emerald", "Life Ring", "Dragon Necklace", "Pirate Voodoo Doll", "Music Sheet", "Terra Rod", "Cultish Symbol", "Broken Key Ring"],
        desc: "Os Acolytes of the Cult receberam algumas instruções nas artes escuras para estarem a disposição do culto. Eles estão orgulhosos de sua posição e são bastante fanáticos sobre o culto. Muitas vezes, pensam que seus poderes os tornam invencíveis, mas sua magia ainda não é tão forte quanto o tamanho de seu ego. Eles apenas respeitam os membros de maior classificação no culto e todos obedecem a seus comandantes como escravos. Acolytes of the Cult usam toda a sua energia para lutar por cargos mais elevados.",
        local: ["Forbidden Temple", "Formorgar Mines", "Hellgorge", "Vandura Cultist Hideout", "Yalahar Magician Quarter"],
    },
    {
        id: 2,
        status: [],
        nome: "Adept of the Cult",
        img: "./src/img/criaturas/adept_of_the_cult.gif",
        hpTotal: 430,
        hp: 430,
        xp: 400,
        stamina: 30,
        velocidade: 95,
        estrela: 3,
        raridade: 1,
        charm: 0,
        ataqueFisico: 100,
        defesa: 33,
        ataqueMagico: [{earth: 0, holy: 0, ice: 0, fire: 0, physical: 0, death: 0, energy: 0, drain: 150}],
        resistencia: [{earth: 40, holy: 30, ice: 20, fire: 0, physical: 0, death: -5, energy: -5, drain: 0}],
        habilidades: [{heal: 80, veneno: 2, drunk: 1.3, haste: 0, paralyze: 0, imuneParalyze: 0, summon: "Ghoul", debuff: 0, invisivel: true, verInvisivel: true}],
        sons: ["Praise the voodoo!", "Power to the cult!", "Feel the power of the cult!"],
        loot: ["Platinum Coin", "Cultish Robe", "Rope Belt", "Pirate Voodoo Doll", "Orange Book", "Time Ring", "Silver Amulet", "Clerical Mace", "Music Sheet", "Amber Staff", "Small Ruby", "Hailstorm Rod", "Red Robe", "Lunar Staff", "Cultish Symbol", "Broken Key Ring"],
        desc: `Adept of the Cult é a mais alta classificação que um cultista normal sonha em adquirir. Com forte vontade, crueldade e astúcia, eles usam os segredos do culto para amplificar a sua magia até um grau ameaçador. Vêem a si mesmos como algo de grande valor para o culto e, por esta razão, estão sempre acompanhados por alguns membros de menor hierarquia para apoiá-los e protegê-los. Eles detêm importantes conhecimentos sobre o culto, são tão fanáticos que preferem morrer do que serem capturados vivos.`,
        local: ["Forbidden Temple", "Formorgar Mines", "Hellgorge", "Vandura Cultist Hideout", "Yalahar Magician Quarter"],
    },
    {
        id: 3,
        status: [],
        nome: "Adult Goanna",
        img: "./src/img/criaturas/adult_goanna.gif",
        hpTotal: 8300,
        hp: 8300,
        xp: 6650,
        stamina: 30,
        velocidade: 210,
        estrela: 4,
        raridade: 1,
        charm: 50,
        ataqueFisico: 400,
        defesa: 84,
        ataqueMagico: [{earth: 1360, holy: 0, ice: 0, fire: 0, physical: 0, death: 0, energy: 0, drain: 0}],
        resistencia: [{earth: 25, holy: 0, ice: 0, fire: 0, physical: 0, death: 0, energy: -10, drain: 0}],
        habilidades: [{heal: 0, veneno: 19, drunk: 0, haste: 75, paralyze: 0, imuneParalyze: true, summon: 0, debuff: 0, invisivel: 0, verInvisivel: true}],
        sons: ["Tsss!"],
        loot: ["Platinum Coin", "Envenomed Arrow", "Earth Arrow", "Small Sapphires", "Small Enchanted Emerald", "Terra Amulet", "Terra Hood", "Emerald Bangle", "Terra Rod", "Blue Crystal Shard", "Green Crystal Splinter", "Red Goanna Scale", "Goanna Meat", "Silver Brooch", "White Pearl", "Small Amethyst", "Yellow Gem", "Green Gem", "Serpent Sword", "Wood Cape", "Sacred Tree Amulet", "Fur Armor", "Onyx Chip", "Opal", "Coral Brooch", "Gemmed Figurine", "Lizard Heart", "Scared Frog", "Goanna Claw"],
        desc: `As Goannas são grandes lagartos predadores com dentes e garras afiadas. Eles têm pele grossa com camuflagem que varia de faixas e listras para manchas e círculos. A cor da pele muda à medida que as criaturas amadurecem, com os juvenis sendo azuis e os animais adultos com vermelho vivo. Goannas põem ovos em um ninho ou toca, mas às vezes também dentro de cupinzeiros, que oferecem proteção, bem como incubação. Além disso, os cupins fornecem uma refeição para os jovens quando eclodem. Os ovos de Goanna são uma refeição procurada pela população humana de Kilmaresh. Mas como obtê-los é uma tarefa perigosa, eles fazem um menu bastante caro. Goannas são encontrados em todas as estepes de Kilmaresh. Eles atacam insetos, lagartos menores, cobras, pássaros, mamíferos e também humanos se tiverem a chance de fazê-lo. Mas eles também são comedores de carniça e, portanto, atraídos pela carne apodrecida. Há um debate se os goannas são venenosos ou não. É um facto que as mordidas de goannas causam hemorragias incessantes e muitos sábios presumem que isto se deve a glândulas produtoras de toxinas na boca dos lagartos.`,
        local: ["Kilmaresh"],
    },
    {
        id: 4,
        status: [],
        nome: "Afflicted Strider",
        img: "./src/img/criaturas/afflicted_strider.gif",
        hpTotal: 10000,
        hp: 10000,
        xp: 5700,
        stamina: 30,
        velocidade: 135,
        estrela: 4,
        raridade: 1,
        charm: 50,
        ataqueFisico: 280,
        defesa: 68,
        ataqueMagico: [{earth: 0, holy: 0, ice: 0, fire: 500, physical: 0, death: 0, energy: 0, drain: 0}],
        resistencia: [{earth: 10, holy: 0, ice: 0, fire: -10, physical: 5, death: 15, energy: 0, drain: 0}],
        habilidades: [{heal: 0, veneno: 0, drunk: 1.4, haste: 0, paralyze: 0, imuneParalyze: true, summon: 0, debuff: 0, invisivel: 0, verInvisivel: true}],
        sons: ["Knorror norror"],
        loot: ["Platinum Coin", "Violet Gem", "Guardian Halberd", "Crystal Sword", "Violet Crystal Shard", "Green Crystal Shard", "Afflicted Strider Worm" , "Afflicted Strider Head", "Magma Coat", "Ice Rapier", "Serpent Sword", "Broadsword", "Machete", "Knight Axe", "Knight Armor", "Doublet", "Haunted Blade", "Titan Axe", "Mercenary Sword", "Spirit Cloak", "Focus Cape", "Belted Cape"],
        desc: `Os striders aflitos são propositadamente infectados por um parasita raro que altera significativamente sua fisiologia e psique. Parece torná-los mais agressivos e fisicamente capazes, embora também reduza significativamente sua vida útil. Aqueles abaixo sempre mostraram pouca contenção em usar tais métodos em desconsideração de seus servos, mas tais táticas e com eles a implantação de striders aflitos tornaram-se mais comuns recentemente. Isso pode sugerir uma mudança de liderança ou estratégia.`,
        local: ["Antrum of the Fallen"],
    },
    {
        id: 5,
        status: [],
        nome: "Amazon",
        img: "./src/img/criaturas/amazon.gif",
        hpTotal: 110,
        hp: 110,
        xp: 60,
        stamina: 30,
        velocidade: 86,
        estrela: 2,
        raridade: 1,
        charm: 15,
        ataqueFisico: 20,
        defesa: 11,
        ataqueMagico: [{earth: 0, holy: 0, ice: 0, fire: 0, physical: 30, death: 0, energy: 0, drain: 0}],
        resistencia: [{earth: 0, holy: 0, ice: 0, fire: 0, physical: -5, death: -5, energy: 0, drain: 0}],
        habilidades: [{heal: 0, veneno: 0, drunk: 0, haste: 0, paralyze: 0, imuneParalyze: 0, summon: 0, debuff: 0, invisivel: 0, verInvisivel: 0}],
        sons: ["Your head shall be mine!", "Your head will be mine!", "Yeeee ha!"],
        loot: ["Ankrahmun Pharaoh Tombs", "Amazon Camp", "Amazon Tower", "Corym Black Market", "Laguna Islands", "Yalahar Foreigner Quarter", "Yalahar Trade Quarter"],
        desc: `Amazonas são mulheres guerreiras que construíram uma comunidade escondida nos pântanos ao leste em Tibia. Elas atacam qualquer intruso de sua comunidade vigorosamente e cortam as cabeças de suas vítimas para mantê-las como algum tipo de troféu. Elas não são muito fortes no combate corpo a corpo, porém são capazes de lançar facas com uma precisão mortal. Uma amazona que coleta 13 cabeças é promovida à Valkyrie. Elas são mulheres selvagens que lutam por sua liberdade e odeiam quando alguém invade seu território.`,
        local: ["Gold Coin", "Skull", "Dagger", "Brown Bread", "Sabre", "Girlish Hair Decoration", "Protective Charm", "Torch", "Crystal Necklace", " Small Ruby", "Silver Raid Token"],
    },
    {
        id: 6,
        status: [],
        nome: "Ancient Scarab",
        img: "./src/img/criaturas/ancient_scarab.gif",
        hpTotal: 1000,
        hp: 1000,
        xp: 720,
        stamina: 30,
        velocidade: 109,
        estrela: 3,
        raridade: 1,
        charm: 25,
        ataqueFisico: 200,
        defesa: 36,
        ataqueMagico: [{earth: 140, holy: 0, ice: 0, fire: 0, physical: 0, death: 0, energy: 0, drain: 0}],
        resistencia: [{earth: 100, holy: 0, ice: -5, fire: -20, physical: 10, death: 0, energy: 20, drain: 0}],
        habilidades: [{heal: 0, veneno: 26, drunk: 0, haste: 25, paralyze: true, imuneParalyze: true, summon: "Larva", debuff: 0, invisivel: 0, verInvisivel: true}],
        sons: ["Ahhhh..."],
        loot: ["Gold Coin", "Scarab Coin", "Small Amethyst", "Small Emerald", "Magic Light Wand", "Scarab Pincers", "Strong Health Potion", "Ancient Amulet", "Plate Armor", "Scarab Amulet", "Scarab Shield", "Springsprout Rod", "Daramian Waraxe", "Terra Hood", "Silver Raid Token"],
        desc: `O Ancient Scarab é realmente antigo, é dito que algumas espécies vivem há séculos. Rumores dizem que a menos que seja morto, um scarab não morrerá de velhice e continuará a crescer até atingir enormes proporções. Seu ritmo natural de movimentação não é muito rápido, mas são capazes de atingir, bruscamente, altas velocidades para pegar seus oponentes com a guarda baixa. Ainda mais perigoso, seu veneno é forte o suficiente para permitir à estas criaturas criarem nuvens fedorentas de destruições e mortes aos seus redores.`,
        local: ["Ankrahmun Pharaoh Tombs", "Beregar Cave", "Demon Forge", "Fenrock", "Larva Caves", "Lion's Rock", "Mother of Scarabs Lair", "Middle Spike", "Scarabs Lair", "Yalahar Arena Quarter"],
    },
    {
        id: 7,
        status: [],
        nome: "Animated Feather",
        img: "./src/img/criaturas/animated_feather.gif",
        hpTotal: 13000,
        hp: 13000,
        xp: 9860,
        stamina: 30,
        velocidade: 210,
        estrela: 4,
        raridade: 1,
        charm: 50,
        ataqueFisico: 600,
        defesa: 79,
        ataqueMagico: [{earth: 0, holy: 0, ice: 3650, fire: 0, physical: 0, death: 0, energy: 0, drain: 0}],
        resistencia: [{earth: 0, holy: 0, ice: 100, fire: -18, physical: 0, death: 0, energy: 0, drain: 0}],
        habilidades: [{heal: 0, veneno: 0, drunk: 0, haste: 0, paralyze: 0, imuneParalyze: true, summon: 0, debuff: 0, invisivel: 0, verInvisivel: true}],
        sons: ["scribble scribble", "*scraaaatch*"],
        loot: ["Platinum Coin", "Small Sapphire", "Glowing Rune", "Glacier Mask", "Energy Ring", "Ice Cube", "Ultimate Mana Potion", "Quill", "Glacier Amulet", "Golden Mug", "Small Diamond", "Life Crystal", "Hailstorm Rod", "Crystal Mace", "Diamond Sceptre", "Sapphire Hammer", "Glacial Rod", "Crystalline Armor", "Leviathan's Amulet"],
        desc: `Animated Feathers são criadas para serem simples golens que servem como copistas e escribas automáticos. Não espetacular e não podendo falar por si, eles são meras ferramentas para mágicos poderosos. Há rumores, de penas antigas que copiaram tantos textos arcanos, que alguns dos conhecimentos acumularam gradualmente neles. Lenta mas firmemente, eles crescem em poder e com poder de sentir. Sendo assim, eles adquiriram algum tipo de autoconsciência.`,
        local: ["Secret Library Ice Section"],
    },
    {
        id: 8,
        status: [],
        nome: "Arachnophobica",
        img: "./src/img/criaturas/arachnophobica.gif",
        hpTotal: 5000,
        hp: 5000,
        xp: 4700,
        stamina: 30,
        velocidade: 200,
        estrela: 4,
        raridade: 1,
        charm: 50,
        ataqueFisico: 450,
        defesa: 70,
        ataqueMagico: [{earth: 0, holy: 0, ice: 0, fire: 0, physical: 0, death: 1100, energy: 650, drain: 0}],
        resistencia: [{earth: 0, holy: -40, ice: 0, fire: 0, physical: 0, death: 50, energy: 50, drain: 0}],
        habilidades: [{heal: 0, veneno: 0, drunk: 0, haste: 0, paralyze: 0, imuneParalyze: true, summon: 0, debuff: 0, invisivel: 0, verInvisivel: true}],
        sons: ["Tip tap tip tap!", "Zip zip zip!!!"],
        loot: ["Platinum Coin", "Great Spirit Potion", "Silver Amulet", "Sword Ring", "Spider Fangs", "Essence of a Bad Dream", "Magma Amulet", "Power Ring", "Energy Ring", "Life Ring", "Platinum Amulet", "Orb", "Mind Stone", "Wand of Cosmic Energy", "Elven Amulet", "Garlic Necklace", "Axe Ring", "Ring of Healing", "Spider Silk", "Death Ring", "Underworld Rod", "Sacred Tree Amulet", "Ring of Blue Plasma", "Collar of Red Plasma", "Strange Talisman", "Strange Symbol", "Stone Skin Amulet", "Necklace of the Deep", "Collar of Green Plasma"],
        desc: `O pesadelo crescente que tomou conta dos reinos dos nascidos dos sonhos distorceu e deformaram grande parte da vida animal desses lugares. Foi a aracnofóbica que pôs fim à maioria deles. É um ponto mudo discutir se a aracnofóbica é uma forma retorcida da Giant Spider, uma aranha comum aumentada e mutada ou nasceu de medos subconscientes.`,
        local: ["Buried Cathedral", "Haunted Nexus", "Dream Labyrinth"],
    },
    {
        id: 9,
        status: [],
        nome: "Arctic Faun",
        img: "./src/img/criaturas/arctic_faun.gif",
        hpTotal: 300,
        hp: 300,
        xp: 300,
        stamina: 30,
        velocidade: 105,
        estrela: 3,
        raridade: 2,
        charm: 25,
        ataqueFisico: 100,
        defesa: 30,
        ataqueMagico: [{earth: 0, holy: 0, ice: 80, fire: 0, physical: 0, death: 0, energy: 0, drain: 0}],
        resistencia: [{earth: 70, holy: 30, ice: 80, fire: -15, physical: 10, death: 20, energy: -10, drain: 0}],
        habilidades: [{heal: 50, veneno: 0, drunk: 0, haste: 0, paralyze: 0, imuneParalyze: true, summon: 0, debuff: 0, invisivel: 0, verInvisivel: true}],
        sons: ["Wine, women and song!", "Dance with me!", "In vino veritas! Hahaha!"],
        loot: ["Gold Coin", "Cookies", "Fresh Fruit", "Leaf Star", "Dandelion Seeds", "Goat Grass", "Shimmering Beetles", "Strong Health Potion", "Rainbow Quartz", "Small Stone", "Grapes", "Great Health Potion", "Panpipes", "Wood Cape", "Die", "Leaf Legs", "Wooden Spellbook"],
        desc: `Sem nenhuma informação!`,
        local: ["Ice Islands"],
    },
    {
        id: 10,
        status: [],
        nome: "Armadile",
        img: "./src/img/criaturas/Armadile.gif",
        hpTotal: 3800,
        hp: 3800,
        xp: 2900,
        stamina: 30,
        velocidade: 220,
        estrela: 4,
        raridade: 2,
        charm: 50,
        ataqueFisico: 0,
        defesa: 66,
        ataqueMagico: [{earth: 0, holy: 0, ice: 0, fire: 100, physical: 0, death: 0, energy: 0, drain: 550}],
        resistencia: [{earth: 100, holy: 15, ice: 15, fire: 20, physical: 5, death: 45, energy: 15, drain: 0}],
        habilidades: [{heal: 0, veneno: 0, drunk: 0, haste: 0, paralyze: 0, imuneParalyze: true, summon: 0, debuff: 0, invisivel: true, verInvisivel: true}],
        sons: ["Creak!"],
        loot: ["Gold Coin", "Platinum Coin", "Mana Potion", "Strong Health Potion", "Strong Mana Potion", "Great Health Potion", "Great Mana Potion", "Drill Bolt", "Envenomed Arrow", "Green Crystal Fragment", "Battle Stone", "Coal", "Crystalline Spike", "Green Crystal Splinter", "Terra Boots", "Time Ring", "Titan Axe", "Tower Shield", "Bonebreaker", "Crystalline Armor"],
        desc: `Os gnomos contam histórias que os Armadiles alguma vez viveram nas profundezas de cavernas fechadas junto de outras criaturas, em harmonia. Devido a atividades sísmicas o seu habitat natural foi destruído, mas eles conseguiram escapar dentro de um túnel subterrâneo que se abriu. No novo ambiente eles conseguiam escapar mais fácil dos seus predadores naturais e tinham menos competição por alimento.`,
        local: ["Gnomegate Fungus Dungeon"],
    },
    {
        id: 11,
        status: ["Assassin"],
        nome: "",
        img: "./src/img/criaturas/assassin.gif",
        hpTotal: 175,
        hp: 175,
        xp: 105,
        stamina: 30,
        velocidade: 112,
        estrela: 2,
        raridade: 1,
        charm: 15,
        ataqueFisico: 120,
        defesa: 17,
        ataqueMagico: [{earth: 0, holy: 0, ice: 0, fire: 0, physical: 35, death: 0, energy: 0, drain: 0}],
        resistencia: [{earth: 0, holy: 0, ice: 0, fire: 0, physical: -10, death: -5, energy: 0, drain: 0}],
        habilidades: [{heal: 0, veneno: 0, drunk: 1.2, haste: 0, paralyze: 0, imuneParalyze: 0, summon: 0, debuff: 0, invisivel: true, verInvisivel: true}],
        sons: ["You are on my deathlist!", "Die!", "Feel the hand of death!"],
        loot: ["Torch", "Gold Coin", "Throwing Star", "Knife", "SemiCombat Knife", "Steel Helmet", "Plate Shield", "Battle Shield", "Viper StarsLeopard Armor", "Steel Shield", "Small Diamond", "Horseman Helmet"],
        desc: `Implacável e letal, o Assassino utiliza traiçoeiros ataques surpresas. Embora haja muitos criminosos, bandidos e assassinos que vagam pelo reino, o assassino é um dos poucos que fez do assassinato uma verdadeira profissão.`,
        local: ["Dark Cathedral", "Yalahar Factory Quarter", "Yalahar Trade Quarter"],
    },
    {
        id: 12,
        status: [],
        nome: "Azure Frog",
        img: "./src/img/criaturas/Azure_Frog.gif",
        hpTotal: 60,
        hp: 60,
        xp: 20,
        stamina: 30,
        velocidade: 160,
        estrela: 2,
        raridade: 1,
        charm: 15,
        ataqueFisico: 20,
        defesa: 8,
        ataqueMagico: [{earth: 0, holy: 0, ice: 0, fire: 0, physical: 0, death: 0, energy: 0, drain: 0}],
        resistencia: [{earth: 0, holy: 0, ice: 10, fire: -10, physical: 0, death: 0, energy: 0, drain: 0}],
        habilidades: [{heal: 0, veneno: 0, drunk: 0, haste: 0, paralyze: 0, imuneParalyze: true, summon: 0, debuff: 0, invisivel: 0, verInvisivel: true}],
        sons: ["Ribbit!", "Ribbit! Ribbit!"],
        loot: ["Gold Coin", "Worm", "Bunch of Winterberrie", "Envelope from the Wizard", "Fireworks Rocket", "Party Hat", "Party Trumpet", "Snowball"],
        desc: `Os sapos aparecem em diferentes formas, cores e tamanhos. O mais comum, é o verde, que pode ser encontrado em quase todos os lagos ou qualquer outro pedaço de água contanto que o clima não seja muito frio. Enquanto o verde é inofensivo e só ameaça moscas e outros insetos, a flora e a fauna agressiva no sul criaram várias subespécies de sapos.`,
        local: ["Emerald Gardens", "Fading Isles", "Laguna Islands", "Meriana", "Murmuring Wilderness", "Sparkling Lagoon"],
    },
    {
        id: 13,
        status: [],
        nome: "Badger",
        img: "./src/img/criaturas/Badger.gif",
        hpTotal: 23,
        hp: 23,
        xp: 5,
        stamina: 30,
        velocidade: 70,
        estrela: 1,
        raridade: 1,
        charm: 5,
        ataqueFisico: 10,
        defesa: 1,
        ataqueMagico: [{earth: 0, holy: 0, ice: 0, fire: 0, physical: 0, death: 0, energy: 0, drain: 0}],
        resistencia: [{earth: 0, holy: 0, ice: 0, fire: 0, physical: 0, death: 0, energy: 0, drain: 0}],
        habilidades: [{heal: 0, veneno: 0, drunk: 0, haste: 0, paralyze: 0, imuneParalyze: 0, summon: 0, debuff: 0, invisivel: 0, verInvisivel: 0}],
        sons: ["Ahhhh..."],
        loot: ["Beetroot", "Badger Fur", "Acorn", "Silver Raid Token"],
        desc: `Criaturas comuns nas florestas de planícies Tibianas. Embora normalmente sejam bastante assustados, estes animais são extremamente territoriais. Prontos para atacar qualquer intruso independente do tamanho. O Badger pode facilmente tornar-se uma desagradável surpresa para viajantes despreparados.`,
        local: ["AbDendriel", "Bittermor", "Cormaya", "Dawnport", "Deepling Temple Complex", "Edron", "Grimvale", "Krimhorn", "Ragnir, Svargrond", "Yalahar Factory Quarter"],
    },
    {
        id: 14,
        status: [],
        nome: "Bandit",
        img: "./src/img/criaturas/Bandit.gif",
        hpTotal: 245,
        hp: 245,
        xp: 65,
        stamina: 30,
        velocidade: 90,
        estrela: 2,
        raridade: 1,
        charm: 15,
        ataqueFisico: 43,
        defesa: 11,
        ataqueMagico: [{earth: 0, holy: 0, ice: 0, fire: 0, physical: 0, death: 0, energy: 0, drain: 0}],
        resistencia: [{earth: 0, holy: 0, ice: 0, fire: 0, physical: -10, death: -5, energy: 0, drain: 0}],
        habilidades: [{heal: 0, veneno: 0, drunk: 0, haste: 0, paralyze: 0, imuneParalyze: true, summon: 0, debuff: 0, invisivel: 0, verInvisivel: true}],
        sons: ["Hand me your purse!", "Your money or your life!"],
        loot: ["Gold Coin", "Axe", "Mace", "Brass Shield", "Leather Legs", "Tomato", "Chain Helmet", "Brass Armor", "Iron Helmet"],
        desc: `O conto do bandido nobre que toma dos ricos e dá aos pobres está longe da realidade. Comumente, ele não se importa com quem está roubando contanto que consiga ganhar algo de valor para ele mesmo. Na realidade, na maioria dos casos, os pobres são aqueles que estão pior preparados para se defenderem e então se tornaram suas vítimas preferidas.`,
        local: ["Bandit Caves", "Dark Cathedral", "Formorgar Mines", "Grimvale", "Kha'zeel Mountains", "Outlaw Camp", "Plains of Havoc", "Thais", "The Cave", "Tyrsung", "Voodoo Grounds", "Yalahar Factory Quarter", "Yalahar Foreigner Quarter", "Yalahar Trade Quarter"],
    },
    {
        id: 15,
        status: [],
        nome: "Banshee",
        img: "./src/img/criaturas/Banshee.gif",
        hpTotal: 1000,
        hp: 1000,
        xp: 900,
        stamina: 30,
        velocidade: 110,
        estrela: 3,
        raridade: 1,
        charm: 25,
        ataqueFisico: 65,
        defesa: 25,
        ataqueMagico: [{earth: 0, holy: 0, ice: 0, fire: 0, physical: 0, death: 320, energy: 0, drain: 220}],
        resistencia: [{earth: 100, holy: -25, ice: 0, fire: 100, physical: 0, death: 100, energy: 0, drain: 0}],
        habilidades: [{heal: 170, veneno: 4, drunk: 0, haste: 0, paralyze: true, imuneParalyze: 0, summon: 0, debuff: 0, invisivel: 0, verInvisivel: 0}],
        sons: ["Dance for me your dance of death!", "Let the music play!", "I will mourn your death!", "Are you ready to rock?", "Feel my gentle kiss of death.", "That's what I call easy listening!", "IIIIEEEeeeeeehhhHHHH!"],
        loot: ["Gold Coin", "Candlestick", "Silver Amulet", "Simple Dress", "Crystal Ring", "Black Pearl", "Hair of a Banshee", "Petrified Scream", "Poison Dagger", "Silver Brooch", "Strong Mana Potion", "Blue Robe", "Lyre", "Ring of Healing", "Spellbook", "Stone Skin Amulet", "Wedding Ring", "White Pearl", "Life Crystal", "Red Robe", "Sweet Smelling Bait", "Terra Mantle", "Silver Raid Token"],
        desc: `Banshee é uma criatura morta-viva de puro terror. Diz a lenda que ela era uma mulher mortal de grande beleza que se matou por um motivo há muito esquecido. Mas, a morte recusou seu sacrifício e a enviou de volta, amaldiçoada e deformada.`,
        local: ["Ankrahmun Pharaoh Tombs", "Banshee Temple", "Demon Hell", "Drefia Grim Reaper Halls", "Drefia Spirit Grounds", "Drefia Vampire Crypts", "Ghostlands", "Infected Area", "Jakundaf Desert", "Pits of Damnation", "Plains of Havoc", "Underground Isle", "Vengoth", "White Flower Temple", "Yalahar Cemetery Quarter"],
    },
    {
        id: 16,
        status: [],
        nome: "Barbarian Bloodwalker",
        img: "./src/img/criaturas/Barbarian_Bloodwalker.gif",
        hpTotal: 305,
        hp: 305,
        xp: 195,
        stamina: 30,
        velocidade: 118,
        estrela: 3,
        raridade: 1,
        charm: 25,
        ataqueFisico: 170,
        defesa: 9,
        ataqueMagico: [{earth: 0, holy: 0, ice: 0, fire: 0, physical: 0, death: 0, energy: 0, drain: 0}],
        resistencia: [{earth: -5, holy: 20, ice: 50, fire: 0, physical: 10, death: -10, energy: 10, drain: 0}],
        habilidades: [{heal: 0, veneno: 0, drunk: 0, haste: 25, paralyze: 0, imuneParalyze: 0, summon: 0, debuff: 0, invisivel: 0, verInvisivel: 0}],
        sons: ["YAAAHEEE!", "SLAUGHTER!", "CARNAGE!", "You can run but you can't hide"],
        loot: ["Gold Coin", "Lamp", "Battle Axe", "Halberd", "Chain Helmet", "Chain Armor", "Ham", "Health Potion", "Red Piece of Cloth", "Beastslayer Axe", "Shard", "Fur Boots", "Silver Raid Token"],
        desc: `Certamente, esta classe de barbáros não foi assim denominada por seu talento diplomático. Um Bloodwalker bate primeiro e depois bate ainda mais.`,
        local: ["Bittermor", "Krimhorn", "Ragnir, Svargrond", "Yalahar Arena Quarter"],
    },
    {
        id: 17,
        status: [],
        nome: "Barbarian Brutetamer",
        img: "./src/img/criaturas/Barbarian_Brutetamer.gif",
        hpTotal: 145,
        hp: 145,
        xp: 90,
        stamina: 30,
        velocidade: 89,
        estrela: 2,
        raridade: 1,
        charm: 15,
        ataqueFisico: 20,
        defesa: 8,
        ataqueMagico: [{earth: 0, holy: 0, ice: 34, fire: 0, physical: 10, death: 0, energy: 0, drain: 0}],
        resistencia: [{earth: 0, holy: 0, ice: 0, fire: 0, physical: 0, death: 0, energy: 0, drain: 0}],
        habilidades: [{heal: 40, veneno: 0, drunk: 0, haste: 0, paralyze: 0, imuneParalyze: true, summon: "War Wolf", debuff: 1, invisivel: 0, verInvisivel: true}],
        sons: ["To me, creatures of the wild!", "My instincts tell me about your cowardice.", "Feel the power of the beast!"],
        loot: ["Gold Coins", "Staff", "Chain Armor", "Corncob", "Fur Bag", "Grey Small Book", "Hunting Spear", "Mana Potion", "Brutetamers Staff", "Mammoth Fur Cape", "Fur Boots", "Mammoth Fur Shorts", "Silver Raid Token"],
        desc: `As Barbarians Brutetamers são mulheres que fracassaram nos testes para se tornarem xamãs verdadeiras. Diferentemente dos invasores masculinos, que ou possuem totais poderes mágicos ou total falta deste talento, as mulheres demonstram ter um certo poder mágico inerente.`,
        local: ["Bittermor", "Fenrock", "Krimhorn", "Ragnir"],
    },
    {
        id: 18,
        status: [],
        nome: "Barbarian Headsplitter",
        img: "./src/img/criaturas/Barbarian_Headsplitter.gif",
        hpTotal: 100,
        hp: 100,
        xp: 85,
        stamina: 30,
        velocidade: 84,
        estrela: 2,
        raridade: 1,
        charm: 15,
        ataqueFisico: 50,
        defesa: 7,
        ataqueMagico: [{earth: 0, holy: 0, ice: 0, fire: 0, physical: 60, death: 0, energy: 0, drain: 0}],
        resistencia: [{earth: -10, holy: 20, ice: 50, fire: 0, physical: 0, death: -10, energy: 20, drain: 0}],
        habilidades: [{heal: 0, veneno: 0, drunk: 0, haste: 0, paralyze: 0, imuneParalyze: true, summon: 0, debuff: 0, invisivel: 0, verInvisivel: 0}],
        sons: ["I will regain my honor with your blood!", "Surrender is not option!", "Its you or me!", "Die! Die! Die!"],
        loot: ["Torch", "Gold Coin", "Knife", "Brass Helmet", "Skull", "Viking Helmet", "Scale Armor", "Health Potion", "Brown Piece of Cloth", "Life Ring", "Fur Boots", "Krimhorn Helmet", "Silver Raid Token"],
        desc: `Os Barbarians Headsplitters são lutadores à distância evitados pelos outros guerreiros. Por terem falhado em batalhas anteriores, devido a sua covardia ou falta de habilidade, são privados, pelos demais bárbaros, da honra de encarar o inimigo face a face.`,
        local: ["Bittermor", "Fenrock", "Krimhorn", "Ragnir", "Svargrond", "Yalahar Foreigner Quarter", "Yalahar Trade Quarter"],
    },
    {
        id: 19,
        status: [],
        nome: "Barbarian Skullhunter",
        img: "./src/img/criaturas/Barbarian_Skullhunter.gif",
        hpTotal: 135,
        hp: 135,
        xp: 85,
        stamina: 30,
        velocidade: 84,
        estrela: 2,
        raridade: 1,
        charm: 15,
        ataqueFisico: 65,
        defesa: 8,
        ataqueMagico: [{earth: 0, holy: 0, ice: 0, fire: 0, physical: 0, death: 0, energy: 0, drain: 0}],
        resistencia: [{earth: -10, holy: 10, ice: 50, fire: 0, physical: 10, death: -5, energy: 20, drain: 0}],
        habilidades: [{heal: 0, veneno: 0, drunk: 0, haste: 0, paralyze: 0, imuneParalyze: true, summon: 0, debuff: 0, invisivel: 0, verInvisivel: 0}],
        sons: ["You will become my trophy.", "Fight harder, coward.", "Show that you are a worthy opponent."],
        loot: ["Torch", "Gold Coins", "Knife", "Brass Helmet", "Viking Helmet", "Skull", "Scale Armor", "Health Potion", "Brown Piece of Cloth", "Life Ring", "Fur Boots", "Crystal Sword", "Ragnir Helmet", "Silver Raid Token"],
        desc: `Um jovem bárbaro começa sua carreira de guerra no posto de Skullhunter por acreditarem que crânios carregam a essência dos inimigos. É a meta de cada jovem conquistar a maior quantidade de crânios possível. Sob a guarda da rainha dos xamãs, se tornou irrelevante se o crânio pertence a um oponente animal ou humano.`,
        local: ["Bittermor", "Fenrock", "Krimhorn", "Ragnir", "Svargrond"],
    },
]
