const arrayCriaturas = [
    {
        id: 0,
        nome: "Acid Blob",
        img: "./src/img/criaturas/Acid_Blob.gif",
        hpTotal: 250,
        hp: 250,
        estrela: 3,
        raridade: 1,
        defesa: 3,
        velocidade: 60,
        ataqueFisico: 77,
        ataqueMagico: [{earth: 88, holy: 0, ice: 0, fire: 0, physical: 0, death: 0, energy: 0}],
        habilidades: [{heal: 0, veneno: 0, drunk: 0, haste: 0, paralyze: 0}],
        summon: false,
        verInvisivel: false,
        imuneParalyze: false,
        resistencia: [{earth: 100, holy: 0, ice: 20, fire: -10, physical: 0, death: 100, energy: -10}],
        sons: ["Kzzchhhh"],
        status: [],
        stamina: 30
    },
    {
        id: 1,
        nome: "Acolyte of the Cult",
        img: "./src/img/criaturas/acolyte_of_the_cult.gif",
        hpTotal: 390,
        hp: 390,
        estrela: 3,
        raridade: 1,
        defesa: 30,
        velocidade: 100,
        ataqueFisico: 65,
        ataqueMagico: [{earth: 0, holy: 0, ice: 0, fire: 0, physical: 125, death: 0, energy: 0}],
        habilidades: [{heal: 40, veneno: 40, drunk: 1.3, haste: 0, paralyze: 0}],
        summon: "Skeleton",
        verInvisivel: true,
        imuneParalyze: false,
        resistencia: [{earth: +20, holy: +20, ice: +20, fire: 0, physical: -10, death: -5, energy: -10}],
        sons: ["Praise Voodoo!", "Power to the cult!", "Feel the power of the cult!"],
        status: [],
        stamina: 30
    },
    {
        id: 2,
        nome: "Adept of the Cult",
        img: "./src/img/criaturas/adept_of_the_cult.gif",
        hpTotal: 430,
        hp: 430,
        estrela: 3,
        raridade: 1,
        defesa: 33,
        velocidade: 95,
        ataqueFisico: 100,
        ataqueMagico: [{earth: 0, holy: 0, ice: 0, fire: 0, physical: 150, death: 0, energy: 0}],
        habilidades: [{heal: 40, veneno: 40, drunk: 1.3, haste: 0, paralyze: 0}],
        summon: "Ghoul",
        verInvisivel: true,
        imuneParalyze: false,
        resistencia: [{earth: 40, holy: 30, ice: 20, fire: 0, physical: 0, death: -5, energy: -5}],
        sons: ["Praise the voodoo!", "Power to the cult!", "Feel the power of the cult!"],
        status: [],
        stamina: 30
    },
    {
        id: 3,
        nome: "Adult Goanna",
        img: "./src/img/criaturas/adult_goanna.gif",
        hpTotal: 8300,
        hp: 8300,
        estrela: 4,
        raridade: 1,
        defesa: 84,
        velocidade: 210,
        ataqueFisico: 400,
        ataqueMagico: [{earth: 1360, holy: 0, ice: 0, fire: 0, physical: 0, death: 0, energy: 0}],
        habilidades: [{heal: 0, veneno: 50, drunk: 0, haste: 50, paralyze: 0}],
        summon: false,
        verInvisivel: true,
        imuneParalyze: false,
        resistencia: [{earth: 25, holy: 0, ice: 0, fire: 0, physical: 0, death: 0, energy: -10}],
        sons: [],
        status: [],
        stamina: 30
    },
    {
        id: 4,
        nome: "Afflicted Strider",
        img: "./src/img/criaturas/afflicted_strider.gif",
        hpTotal: 12000,
        hp: 12000,
        estrela: 4,
        raridade: 1,
        defesa: 68,
        velocidade: 135,
        ataqueFisico: 280,
        ataqueMagico: [{earth: 0, holy: 0, ice: 0, fire: 500, physical: 0, death: 0, energy: 0}],
        habilidades: [{heal: 0, veneno: 0, drunk: 1.4, haste: 0, paralyze: 0}],
        summon: false,
        verInvisivel: true,
        imuneParalyze: false,
        resistencia: [{earth: 10, holy: 0, ice: 0, fire: -10, physical: 5, death: 15, energy: 5}],
        sons: [],
        status: [],
        stamina: 30
    },
    {
        id: 5,
        nome: "Amazon",
        img: "./src/img/criaturas/amazon.gif",
        hpTotal: 110,
        hp: 110,
        estrela: 2,
        raridade: 1,
        defesa: 11,
        velocidade: 86,
        ataqueFisico: 20,
        ataqueMagico: [{earth: 0, holy: 0, ice: 0, fire: 0, physical: 30, death: 0, energy: 0}],
        habilidades: [{heal: 0, veneno: 0, drunk: 0, haste: 0, paralyze: 0}],
        summon: false,
        verInvisivel: false,
        imuneParalyze: false,
        resistencia: [{earth: 0, holy: 0, ice: 0, fire: 0, physical: -5, death: -5, energy: 0}],
        sons: ["Your head shall be mine!", "Your head will be mine!", "Yeeee ha!"],
        status: [],
        stamina: 30
    },
    {
        id: 6,
        nome: "Ancient Scarab",
        img: "./src/img/criaturas/ancient_scarab.gif",
        hpTotal: 1000,
        hp: 1000,
        estrela: 3,
        raridade: 1,
        defesa: 36,
        velocidade: 109,
        ataqueFisico: 200,
        ataqueMagico: [{earth: 140, holy: 0, ice: 0, fire: 0, physical: 0, death: 0, energy: 0}],
        habilidades: [{heal: 0, veneno: 40, drunk: 0, haste: 40, paralyze: 0}],
        summon: "Larva",
        verInvisivel: true,
        imuneParalyze: true,
        resistencia: [{earth: 100, holy: 0, ice: -5, fire: -20, physical: 10, death: 0, energy: 20}],
        sons: [],
        status: [],
        stamina: 30
    },
    {
        id: 7,
        nome: "Animated Feather",
        img: "./src/img/criaturas/animated_feather.gif",
        hpTotal: 13000,
        hp: 13000,
        estrela: 4,
        raridade: 1,
        defesa: 79,
        velocidade: 210,
        ataqueFisico: 600,
        ataqueMagico: [{earth: 0, holy: 0, ice: 3650, fire: 0, physical: 0, death: 0, energy: 0}],
        habilidades: [{heal: 0, veneno: 0, drunk: 0, haste: 0, paralyze: 0}],
        summon: false,
        verInvisivel: true,
        imuneParalyze: true,
        resistencia: [{earth: 0, holy: 0, ice: 100, fire: -18, physical: 0, death: 0, energy: 0}],
        sons: ["scribble scribble", "*scraaaatch*"],
        status: [],
        stamina: 30
    },
    {
        id: 8,
        nome: "Arachnophobica",
        img: "./src/img/criaturas/arachnophobica.gif",
        hpTotal: 5000,
        hp: 5000,
        estrela: 4,
        raridade: 1,
        defesa: 70,
        velocidade: 200,
        ataqueFisico: 450,
        ataqueMagico: [{earth: 0, holy: 0, ice: 0, fire: 0, physical: 0, death: 1100, energy: 650}],
        habilidades: [{heal: 0, veneno: 0, drunk: 0, haste: 0, paralyze: 0}],
        summon: false,
        verInvisivel: true,
        imuneParalyze: false,
        resistencia: [{earth: 0, holy: -40, ice: 0, fire: 0, physical: 0, death: 50, energy: 50}],
        sons: ["Tip tap tip tap!", "Zip zip zip!!!"],
        status: [],
        stamina: 30
    },
    {
        id: 9,
        nome: "Arctic Faun",
        img: "./src/img/criaturas/arctic_faun.gif",
        hpTotal: 300,
        hp: 300,
        estrela: 3,
        raridade: 2,
        defesa: 30,
        velocidade: 105,
        ataqueFisico: 100,
        ataqueMagico: [{earth: 0, holy: 0, ice: 80, fire: 0, physical: 0, death: 0, energy: 0}],
        habilidades: [{heal: 50, veneno: 0, drunk: 0, haste: 0, paralyze: 0}],
        summon: false,
        verInvisivel: false,
        imuneParalyze: false,
        resistencia: [{earth: 70, holy: 30, ice: 80, fire: -15, physical: 10, death: 20, energy: -10}],
        sons: ["Wine, women and song!", "Dance with me!", "In vino veritas! Hahaha!"],
        status: [],
        stamina: 30
    },
]